ACTIVE_PROFILE: dev

POSTGRES_USERNAME: kara
POSTGRES_PASSWORD: mhd02042017
POSTGRES_HOST: 127.0.0.1
POSTGRES_PORT: 5432
POSTGRES_DATABASE: medilabo_authorization

USER_NAME: admin
PASSWORD: kara
ROLES: EUREKA_CLIENT

SERVER_PORT: 8761
UI_APP_URL: http://localhost:3000