ACTIVE_PROFILE: dev

PRIVATE_KEY: "private.key"
PUBLIC_KEY: "public.key"

POSTGRES_USERNAME: kara
POSTGRES_PASSWORD: mhd02042017
POSTGRES_HOST: 127.0.0.1
POSTGRES_PORT: 5432
POSTGRES_DATABASE: medilabo_authorization

USER_NAME: admin
PASSWORD: kara
ROLES: EUREKA_CLIENT

SERVER_PORT: 9000
UI_APP_URL: http://localhost:3000


# Logging - DEBUG en dev
logging:
  level:
    com.openclassrooms: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.jdbc: DEBUG