ACTIVE_PROFILE: prod

PRIVATE_KEY:
PUBLIC_KEY:

POSTGRES_HOST: localhost
POSTGRES_PORT: 5432
POSTGRES_USER: kara
POSTGRES_PASSWORD: mhd02042017
POSTGRES_DATABASE: openclassrooms_medical_microservice

USER_NAME: ${USER_NAME}
PASSWORD: ${PASSWORD}
ROLES: ${ROLES}

server: 8080
UI_APP_URL: http://localhost:4200